// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mssql_server/proto/v1/mssql_server.proto

package mssqlserver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddNewVendorReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CreditRating         string   `protobuf:"bytes,2,opt,name=credit_rating,json=creditRating,proto3" json:"credit_rating,omitempty"`
	UrlWeb               string   `protobuf:"bytes,3,opt,name=url_web,json=urlWeb,proto3" json:"url_web,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddNewVendorReq) Reset()         { *m = AddNewVendorReq{} }
func (m *AddNewVendorReq) String() string { return proto.CompactTextString(m) }
func (*AddNewVendorReq) ProtoMessage()    {}
func (*AddNewVendorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{0}
}

func (m *AddNewVendorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddNewVendorReq.Unmarshal(m, b)
}
func (m *AddNewVendorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddNewVendorReq.Marshal(b, m, deterministic)
}
func (m *AddNewVendorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddNewVendorReq.Merge(m, src)
}
func (m *AddNewVendorReq) XXX_Size() int {
	return xxx_messageInfo_AddNewVendorReq.Size(m)
}
func (m *AddNewVendorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddNewVendorReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddNewVendorReq proto.InternalMessageInfo

func (m *AddNewVendorReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddNewVendorReq) GetCreditRating() string {
	if m != nil {
		return m.CreditRating
	}
	return ""
}

func (m *AddNewVendorReq) GetUrlWeb() string {
	if m != nil {
		return m.UrlWeb
	}
	return ""
}

type GetVendorReq struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVendorReq) Reset()         { *m = GetVendorReq{} }
func (m *GetVendorReq) String() string { return proto.CompactTextString(m) }
func (*GetVendorReq) ProtoMessage()    {}
func (*GetVendorReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{1}
}

func (m *GetVendorReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVendorReq.Unmarshal(m, b)
}
func (m *GetVendorReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVendorReq.Marshal(b, m, deterministic)
}
func (m *GetVendorReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVendorReq.Merge(m, src)
}
func (m *GetVendorReq) XXX_Size() int {
	return xxx_messageInfo_GetVendorReq.Size(m)
}
func (m *GetVendorReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVendorReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetVendorReq proto.InternalMessageInfo

func (m *GetVendorReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type PurchaseOrderInfoReq struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurchaseOrderInfoReq) Reset()         { *m = PurchaseOrderInfoReq{} }
func (m *PurchaseOrderInfoReq) String() string { return proto.CompactTextString(m) }
func (*PurchaseOrderInfoReq) ProtoMessage()    {}
func (*PurchaseOrderInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{2}
}

func (m *PurchaseOrderInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseOrderInfoReq.Unmarshal(m, b)
}
func (m *PurchaseOrderInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseOrderInfoReq.Marshal(b, m, deterministic)
}
func (m *PurchaseOrderInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseOrderInfoReq.Merge(m, src)
}
func (m *PurchaseOrderInfoReq) XXX_Size() int {
	return xxx_messageInfo_PurchaseOrderInfoReq.Size(m)
}
func (m *PurchaseOrderInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseOrderInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseOrderInfoReq proto.InternalMessageInfo

func (m *PurchaseOrderInfoReq) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListVendorResp struct {
	VendorInfo           []*VendorInfo `protobuf:"bytes,1,rep,name=vendor_info,json=vendorInfo,proto3" json:"vendor_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListVendorResp) Reset()         { *m = ListVendorResp{} }
func (m *ListVendorResp) String() string { return proto.CompactTextString(m) }
func (*ListVendorResp) ProtoMessage()    {}
func (*ListVendorResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{3}
}

func (m *ListVendorResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListVendorResp.Unmarshal(m, b)
}
func (m *ListVendorResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListVendorResp.Marshal(b, m, deterministic)
}
func (m *ListVendorResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListVendorResp.Merge(m, src)
}
func (m *ListVendorResp) XXX_Size() int {
	return xxx_messageInfo_ListVendorResp.Size(m)
}
func (m *ListVendorResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListVendorResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListVendorResp proto.InternalMessageInfo

func (m *ListVendorResp) GetVendorInfo() []*VendorInfo {
	if m != nil {
		return m.VendorInfo
	}
	return nil
}

type VendorInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	AccNumber            string   `protobuf:"bytes,2,opt,name=acc_number,json=accNumber,proto3" json:"acc_number,omitempty"`
	CreditRating         string   `protobuf:"bytes,3,opt,name=credit_rating,json=creditRating,proto3" json:"credit_rating,omitempty"`
	PreferVendor         bool     `protobuf:"varint,4,opt,name=prefer_vendor,json=preferVendor,proto3" json:"prefer_vendor,omitempty"`
	Active               bool     `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VendorInfo) Reset()         { *m = VendorInfo{} }
func (m *VendorInfo) String() string { return proto.CompactTextString(m) }
func (*VendorInfo) ProtoMessage()    {}
func (*VendorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{4}
}

func (m *VendorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorInfo.Unmarshal(m, b)
}
func (m *VendorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorInfo.Marshal(b, m, deterministic)
}
func (m *VendorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorInfo.Merge(m, src)
}
func (m *VendorInfo) XXX_Size() int {
	return xxx_messageInfo_VendorInfo.Size(m)
}
func (m *VendorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VendorInfo proto.InternalMessageInfo

func (m *VendorInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VendorInfo) GetAccNumber() string {
	if m != nil {
		return m.AccNumber
	}
	return ""
}

func (m *VendorInfo) GetCreditRating() string {
	if m != nil {
		return m.CreditRating
	}
	return ""
}

func (m *VendorInfo) GetPreferVendor() bool {
	if m != nil {
		return m.PreferVendor
	}
	return false
}

func (m *VendorInfo) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

type ListShipMethodResp struct {
	ShipMethod           []*ShipMethod `protobuf:"bytes,1,rep,name=ship_method,json=shipMethod,proto3" json:"ship_method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListShipMethodResp) Reset()         { *m = ListShipMethodResp{} }
func (m *ListShipMethodResp) String() string { return proto.CompactTextString(m) }
func (*ListShipMethodResp) ProtoMessage()    {}
func (*ListShipMethodResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{5}
}

func (m *ListShipMethodResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListShipMethodResp.Unmarshal(m, b)
}
func (m *ListShipMethodResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListShipMethodResp.Marshal(b, m, deterministic)
}
func (m *ListShipMethodResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListShipMethodResp.Merge(m, src)
}
func (m *ListShipMethodResp) XXX_Size() int {
	return xxx_messageInfo_ListShipMethodResp.Size(m)
}
func (m *ListShipMethodResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListShipMethodResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListShipMethodResp proto.InternalMessageInfo

func (m *ListShipMethodResp) GetShipMethod() []*ShipMethod {
	if m != nil {
		return m.ShipMethod
	}
	return nil
}

type ShipMethod struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ShipBase             float32  `protobuf:"fixed32,2,opt,name=ship_base,json=shipBase,proto3" json:"ship_base,omitempty"`
	ShipRate             float32  `protobuf:"fixed32,3,opt,name=ship_rate,json=shipRate,proto3" json:"ship_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShipMethod) Reset()         { *m = ShipMethod{} }
func (m *ShipMethod) String() string { return proto.CompactTextString(m) }
func (*ShipMethod) ProtoMessage()    {}
func (*ShipMethod) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{6}
}

func (m *ShipMethod) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShipMethod.Unmarshal(m, b)
}
func (m *ShipMethod) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShipMethod.Marshal(b, m, deterministic)
}
func (m *ShipMethod) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShipMethod.Merge(m, src)
}
func (m *ShipMethod) XXX_Size() int {
	return xxx_messageInfo_ShipMethod.Size(m)
}
func (m *ShipMethod) XXX_DiscardUnknown() {
	xxx_messageInfo_ShipMethod.DiscardUnknown(m)
}

var xxx_messageInfo_ShipMethod proto.InternalMessageInfo

func (m *ShipMethod) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShipMethod) GetShipBase() float32 {
	if m != nil {
		return m.ShipBase
	}
	return 0
}

func (m *ShipMethod) GetShipRate() float32 {
	if m != nil {
		return m.ShipRate
	}
	return 0
}

type PurchaseOrderHeader struct {
	PurchaseOrderID      uint32   `protobuf:"varint,1,opt,name=PurchaseOrderID,proto3" json:"PurchaseOrderID,omitempty"`
	RevisionNumber       uint32   `protobuf:"varint,2,opt,name=RevisionNumber,proto3" json:"RevisionNumber,omitempty"`
	Status               uint32   `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	EmployeeID           uint32   `protobuf:"varint,4,opt,name=EmployeeID,proto3" json:"EmployeeID,omitempty"`
	VendorID             uint32   `protobuf:"varint,5,opt,name=VendorID,proto3" json:"VendorID,omitempty"`
	ShipMethodID         uint32   `protobuf:"varint,6,opt,name=ShipMethodID,proto3" json:"ShipMethodID,omitempty"`
	OrderDate            string   `protobuf:"bytes,7,opt,name=OrderDate,proto3" json:"OrderDate,omitempty"`
	ShipDate             string   `protobuf:"bytes,8,opt,name=ShipDate,proto3" json:"ShipDate,omitempty"`
	SubTotal             float32  `protobuf:"fixed32,9,opt,name=SubTotal,proto3" json:"SubTotal,omitempty"`
	TaxAmt               float32  `protobuf:"fixed32,10,opt,name=TaxAmt,proto3" json:"TaxAmt,omitempty"`
	Freight              float32  `protobuf:"fixed32,11,opt,name=Freight,proto3" json:"Freight,omitempty"`
	TotalDue             float32  `protobuf:"fixed32,12,opt,name=TotalDue,proto3" json:"TotalDue,omitempty"`
	ModifiedDate         string   `protobuf:"bytes,13,opt,name=ModifiedDate,proto3" json:"ModifiedDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PurchaseOrderHeader) Reset()         { *m = PurchaseOrderHeader{} }
func (m *PurchaseOrderHeader) String() string { return proto.CompactTextString(m) }
func (*PurchaseOrderHeader) ProtoMessage()    {}
func (*PurchaseOrderHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{7}
}

func (m *PurchaseOrderHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseOrderHeader.Unmarshal(m, b)
}
func (m *PurchaseOrderHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseOrderHeader.Marshal(b, m, deterministic)
}
func (m *PurchaseOrderHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseOrderHeader.Merge(m, src)
}
func (m *PurchaseOrderHeader) XXX_Size() int {
	return xxx_messageInfo_PurchaseOrderHeader.Size(m)
}
func (m *PurchaseOrderHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseOrderHeader.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseOrderHeader proto.InternalMessageInfo

func (m *PurchaseOrderHeader) GetPurchaseOrderID() uint32 {
	if m != nil {
		return m.PurchaseOrderID
	}
	return 0
}

func (m *PurchaseOrderHeader) GetRevisionNumber() uint32 {
	if m != nil {
		return m.RevisionNumber
	}
	return 0
}

func (m *PurchaseOrderHeader) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PurchaseOrderHeader) GetEmployeeID() uint32 {
	if m != nil {
		return m.EmployeeID
	}
	return 0
}

func (m *PurchaseOrderHeader) GetVendorID() uint32 {
	if m != nil {
		return m.VendorID
	}
	return 0
}

func (m *PurchaseOrderHeader) GetShipMethodID() uint32 {
	if m != nil {
		return m.ShipMethodID
	}
	return 0
}

func (m *PurchaseOrderHeader) GetOrderDate() string {
	if m != nil {
		return m.OrderDate
	}
	return ""
}

func (m *PurchaseOrderHeader) GetShipDate() string {
	if m != nil {
		return m.ShipDate
	}
	return ""
}

func (m *PurchaseOrderHeader) GetSubTotal() float32 {
	if m != nil {
		return m.SubTotal
	}
	return 0
}

func (m *PurchaseOrderHeader) GetTaxAmt() float32 {
	if m != nil {
		return m.TaxAmt
	}
	return 0
}

func (m *PurchaseOrderHeader) GetFreight() float32 {
	if m != nil {
		return m.Freight
	}
	return 0
}

func (m *PurchaseOrderHeader) GetTotalDue() float32 {
	if m != nil {
		return m.TotalDue
	}
	return 0
}

func (m *PurchaseOrderHeader) GetModifiedDate() string {
	if m != nil {
		return m.ModifiedDate
	}
	return ""
}

type PurchaseOrderDetail struct {
	PurchaseOrderDetailID uint32   `protobuf:"varint,1,opt,name=PurchaseOrderDetailID,proto3" json:"PurchaseOrderDetailID,omitempty"`
	DueDate               string   `protobuf:"bytes,2,opt,name=DueDate,proto3" json:"DueDate,omitempty"`
	OrderQty              uint32   `protobuf:"varint,3,opt,name=OrderQty,proto3" json:"OrderQty,omitempty"`
	ProductID             uint32   `protobuf:"varint,4,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	UnitPrice             uint32   `protobuf:"varint,5,opt,name=UnitPrice,proto3" json:"UnitPrice,omitempty"`
	LineTotal             string   `protobuf:"bytes,6,opt,name=LineTotal,proto3" json:"LineTotal,omitempty"`
	ReceivedQty           string   `protobuf:"bytes,7,opt,name=ReceivedQty,proto3" json:"ReceivedQty,omitempty"`
	RejectedQty           uint32   `protobuf:"varint,8,opt,name=RejectedQty,proto3" json:"RejectedQty,omitempty"`
	StockedQty            uint32   `protobuf:"varint,9,opt,name=StockedQty,proto3" json:"StockedQty,omitempty"`
	ModifiedDate          string   `protobuf:"bytes,10,opt,name=ModifiedDate,proto3" json:"ModifiedDate,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *PurchaseOrderDetail) Reset()         { *m = PurchaseOrderDetail{} }
func (m *PurchaseOrderDetail) String() string { return proto.CompactTextString(m) }
func (*PurchaseOrderDetail) ProtoMessage()    {}
func (*PurchaseOrderDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{8}
}

func (m *PurchaseOrderDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseOrderDetail.Unmarshal(m, b)
}
func (m *PurchaseOrderDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseOrderDetail.Marshal(b, m, deterministic)
}
func (m *PurchaseOrderDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseOrderDetail.Merge(m, src)
}
func (m *PurchaseOrderDetail) XXX_Size() int {
	return xxx_messageInfo_PurchaseOrderDetail.Size(m)
}
func (m *PurchaseOrderDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseOrderDetail.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseOrderDetail proto.InternalMessageInfo

func (m *PurchaseOrderDetail) GetPurchaseOrderDetailID() uint32 {
	if m != nil {
		return m.PurchaseOrderDetailID
	}
	return 0
}

func (m *PurchaseOrderDetail) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *PurchaseOrderDetail) GetOrderQty() uint32 {
	if m != nil {
		return m.OrderQty
	}
	return 0
}

func (m *PurchaseOrderDetail) GetProductID() uint32 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *PurchaseOrderDetail) GetUnitPrice() uint32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *PurchaseOrderDetail) GetLineTotal() string {
	if m != nil {
		return m.LineTotal
	}
	return ""
}

func (m *PurchaseOrderDetail) GetReceivedQty() string {
	if m != nil {
		return m.ReceivedQty
	}
	return ""
}

func (m *PurchaseOrderDetail) GetRejectedQty() uint32 {
	if m != nil {
		return m.RejectedQty
	}
	return 0
}

func (m *PurchaseOrderDetail) GetStockedQty() uint32 {
	if m != nil {
		return m.StockedQty
	}
	return 0
}

func (m *PurchaseOrderDetail) GetModifiedDate() string {
	if m != nil {
		return m.ModifiedDate
	}
	return ""
}

type Product struct {
	ProductID             uint32   `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	ProductNumber         string   `protobuf:"bytes,3,opt,name=ProductNumber,proto3" json:"ProductNumber,omitempty"`
	MakeFlag              bool     `protobuf:"varint,4,opt,name=MakeFlag,proto3" json:"MakeFlag,omitempty"`
	FinishedGoodsFlag     bool     `protobuf:"varint,5,opt,name=FinishedGoodsFlag,proto3" json:"FinishedGoodsFlag,omitempty"`
	Color                 string   `protobuf:"bytes,6,opt,name=Color,proto3" json:"Color,omitempty"`
	SafetyStockLevel      uint32   `protobuf:"varint,7,opt,name=SafetyStockLevel,proto3" json:"SafetyStockLevel,omitempty"`
	ReorderPoint          uint32   `protobuf:"varint,8,opt,name=ReorderPoint,proto3" json:"ReorderPoint,omitempty"`
	StandardCost          uint32   `protobuf:"varint,9,opt,name=StandardCost,proto3" json:"StandardCost,omitempty"`
	ListPrice             uint32   `protobuf:"varint,10,opt,name=ListPrice,proto3" json:"ListPrice,omitempty"`
	Size                  string   `protobuf:"bytes,11,opt,name=Size,proto3" json:"Size,omitempty"`
	SizeUnitMeasureCode   string   `protobuf:"bytes,12,opt,name=SizeUnitMeasureCode,proto3" json:"SizeUnitMeasureCode,omitempty"`
	WeightUnitMeasureCode string   `protobuf:"bytes,13,opt,name=WeightUnitMeasureCode,proto3" json:"WeightUnitMeasureCode,omitempty"`
	Weight                uint32   `protobuf:"varint,14,opt,name=Weight,proto3" json:"Weight,omitempty"`
	DaysToManufacture     uint32   `protobuf:"varint,15,opt,name=DaysToManufacture,proto3" json:"DaysToManufacture,omitempty"`
	ProductLine           string   `protobuf:"bytes,16,opt,name=ProductLine,proto3" json:"ProductLine,omitempty"`
	Class                 string   `protobuf:"bytes,17,opt,name=Class,proto3" json:"Class,omitempty"`
	Style                 string   `protobuf:"bytes,18,opt,name=Style,proto3" json:"Style,omitempty"`
	ProductSubcategoryID  uint32   `protobuf:"varint,19,opt,name=ProductSubcategoryID,proto3" json:"ProductSubcategoryID,omitempty"`
	ProductModelID        uint32   `protobuf:"varint,20,opt,name=ProductModelID,proto3" json:"ProductModelID,omitempty"`
	SellStartDate         string   `protobuf:"bytes,21,opt,name=SellStartDate,proto3" json:"SellStartDate,omitempty"`
	SellEndDate           string   `protobuf:"bytes,22,opt,name=SellEndDate,proto3" json:"SellEndDate,omitempty"`
	DiscontinuedDate      string   `protobuf:"bytes,23,opt,name=DiscontinuedDate,proto3" json:"DiscontinuedDate,omitempty"`
	Rowguid               string   `protobuf:"bytes,24,opt,name=rowguid,proto3" json:"rowguid,omitempty"`
	ModifiedDate          string   `protobuf:"bytes,25,opt,name=ModifiedDate,proto3" json:"ModifiedDate,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{9}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetProductID() uint32 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetProductNumber() string {
	if m != nil {
		return m.ProductNumber
	}
	return ""
}

func (m *Product) GetMakeFlag() bool {
	if m != nil {
		return m.MakeFlag
	}
	return false
}

func (m *Product) GetFinishedGoodsFlag() bool {
	if m != nil {
		return m.FinishedGoodsFlag
	}
	return false
}

func (m *Product) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Product) GetSafetyStockLevel() uint32 {
	if m != nil {
		return m.SafetyStockLevel
	}
	return 0
}

func (m *Product) GetReorderPoint() uint32 {
	if m != nil {
		return m.ReorderPoint
	}
	return 0
}

func (m *Product) GetStandardCost() uint32 {
	if m != nil {
		return m.StandardCost
	}
	return 0
}

func (m *Product) GetListPrice() uint32 {
	if m != nil {
		return m.ListPrice
	}
	return 0
}

func (m *Product) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Product) GetSizeUnitMeasureCode() string {
	if m != nil {
		return m.SizeUnitMeasureCode
	}
	return ""
}

func (m *Product) GetWeightUnitMeasureCode() string {
	if m != nil {
		return m.WeightUnitMeasureCode
	}
	return ""
}

func (m *Product) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Product) GetDaysToManufacture() uint32 {
	if m != nil {
		return m.DaysToManufacture
	}
	return 0
}

func (m *Product) GetProductLine() string {
	if m != nil {
		return m.ProductLine
	}
	return ""
}

func (m *Product) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *Product) GetStyle() string {
	if m != nil {
		return m.Style
	}
	return ""
}

func (m *Product) GetProductSubcategoryID() uint32 {
	if m != nil {
		return m.ProductSubcategoryID
	}
	return 0
}

func (m *Product) GetProductModelID() uint32 {
	if m != nil {
		return m.ProductModelID
	}
	return 0
}

func (m *Product) GetSellStartDate() string {
	if m != nil {
		return m.SellStartDate
	}
	return ""
}

func (m *Product) GetSellEndDate() string {
	if m != nil {
		return m.SellEndDate
	}
	return ""
}

func (m *Product) GetDiscontinuedDate() string {
	if m != nil {
		return m.DiscontinuedDate
	}
	return ""
}

func (m *Product) GetRowguid() string {
	if m != nil {
		return m.Rowguid
	}
	return ""
}

func (m *Product) GetModifiedDate() string {
	if m != nil {
		return m.ModifiedDate
	}
	return ""
}

type ProductVendor struct {
	ProductID            uint32   `protobuf:"varint,1,opt,name=ProductID,proto3" json:"ProductID,omitempty"`
	BusinessEntityID     uint32   `protobuf:"varint,2,opt,name=BusinessEntityID,proto3" json:"BusinessEntityID,omitempty"`
	AverageLeadTime      uint32   `protobuf:"varint,3,opt,name=AverageLeadTime,proto3" json:"AverageLeadTime,omitempty"`
	StandardPrice        uint32   `protobuf:"varint,4,opt,name=StandardPrice,proto3" json:"StandardPrice,omitempty"`
	LastReceiptCost      uint32   `protobuf:"varint,5,opt,name=LastReceiptCost,proto3" json:"LastReceiptCost,omitempty"`
	LastReceiptDate      string   `protobuf:"bytes,6,opt,name=LastReceiptDate,proto3" json:"LastReceiptDate,omitempty"`
	MinOrderQty          uint32   `protobuf:"varint,7,opt,name=MinOrderQty,proto3" json:"MinOrderQty,omitempty"`
	MaxOrderQty          uint32   `protobuf:"varint,8,opt,name=MaxOrderQty,proto3" json:"MaxOrderQty,omitempty"`
	OnOrderQty           uint32   `protobuf:"varint,9,opt,name=OnOrderQty,proto3" json:"OnOrderQty,omitempty"`
	UnitMeasureCode      string   `protobuf:"bytes,10,opt,name=UnitMeasureCode,proto3" json:"UnitMeasureCode,omitempty"`
	ModifiedDate         string   `protobuf:"bytes,11,opt,name=ModifiedDate,proto3" json:"ModifiedDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductVendor) Reset()         { *m = ProductVendor{} }
func (m *ProductVendor) String() string { return proto.CompactTextString(m) }
func (*ProductVendor) ProtoMessage()    {}
func (*ProductVendor) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{10}
}

func (m *ProductVendor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductVendor.Unmarshal(m, b)
}
func (m *ProductVendor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductVendor.Marshal(b, m, deterministic)
}
func (m *ProductVendor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductVendor.Merge(m, src)
}
func (m *ProductVendor) XXX_Size() int {
	return xxx_messageInfo_ProductVendor.Size(m)
}
func (m *ProductVendor) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductVendor.DiscardUnknown(m)
}

var xxx_messageInfo_ProductVendor proto.InternalMessageInfo

func (m *ProductVendor) GetProductID() uint32 {
	if m != nil {
		return m.ProductID
	}
	return 0
}

func (m *ProductVendor) GetBusinessEntityID() uint32 {
	if m != nil {
		return m.BusinessEntityID
	}
	return 0
}

func (m *ProductVendor) GetAverageLeadTime() uint32 {
	if m != nil {
		return m.AverageLeadTime
	}
	return 0
}

func (m *ProductVendor) GetStandardPrice() uint32 {
	if m != nil {
		return m.StandardPrice
	}
	return 0
}

func (m *ProductVendor) GetLastReceiptCost() uint32 {
	if m != nil {
		return m.LastReceiptCost
	}
	return 0
}

func (m *ProductVendor) GetLastReceiptDate() string {
	if m != nil {
		return m.LastReceiptDate
	}
	return ""
}

func (m *ProductVendor) GetMinOrderQty() uint32 {
	if m != nil {
		return m.MinOrderQty
	}
	return 0
}

func (m *ProductVendor) GetMaxOrderQty() uint32 {
	if m != nil {
		return m.MaxOrderQty
	}
	return 0
}

func (m *ProductVendor) GetOnOrderQty() uint32 {
	if m != nil {
		return m.OnOrderQty
	}
	return 0
}

func (m *ProductVendor) GetUnitMeasureCode() string {
	if m != nil {
		return m.UnitMeasureCode
	}
	return ""
}

func (m *ProductVendor) GetModifiedDate() string {
	if m != nil {
		return m.ModifiedDate
	}
	return ""
}

type Employee struct {
	JobTitle             string   `protobuf:"bytes,1,opt,name=JobTitle,proto3" json:"JobTitle,omitempty"`
	Gender               string   `protobuf:"bytes,2,opt,name=Gender,proto3" json:"Gender,omitempty"`
	DepartmentName       string   `protobuf:"bytes,3,opt,name=DepartmentName,proto3" json:"DepartmentName,omitempty"`
	GroupName            string   `protobuf:"bytes,4,opt,name=GroupName,proto3" json:"GroupName,omitempty"`
	Shift                string   `protobuf:"bytes,5,opt,name=Shift,proto3" json:"Shift,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{11}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *Employee) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Employee) GetDepartmentName() string {
	if m != nil {
		return m.DepartmentName
	}
	return ""
}

func (m *Employee) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *Employee) GetShift() string {
	if m != nil {
		return m.Shift
	}
	return ""
}

type PurchaseOrderInfo struct {
	EmployeeInfo         *Employee   `protobuf:"bytes,1,opt,name=employee_info,json=employeeInfo,proto3" json:"employee_info,omitempty"`
	VendorInfo           *VendorInfo `protobuf:"bytes,2,opt,name=vendor_info,json=vendorInfo,proto3" json:"vendor_info,omitempty"`
	ShipMethod           *ShipMethod `protobuf:"bytes,3,opt,name=ship_method,json=shipMethod,proto3" json:"ship_method,omitempty"`
	Status               string      `protobuf:"bytes,4,opt,name=Status,proto3" json:"Status,omitempty"`
	OrderDate            string      `protobuf:"bytes,5,opt,name=OrderDate,proto3" json:"OrderDate,omitempty"`
	ShipDate             string      `protobuf:"bytes,6,opt,name=ShipDate,proto3" json:"ShipDate,omitempty"`
	SubTotal             float32     `protobuf:"fixed32,7,opt,name=SubTotal,proto3" json:"SubTotal,omitempty"`
	TaxAmt               float32     `protobuf:"fixed32,8,opt,name=TaxAmt,proto3" json:"TaxAmt,omitempty"`
	Freight              float32     `protobuf:"fixed32,9,opt,name=Freight,proto3" json:"Freight,omitempty"`
	TotalDue             float32     `protobuf:"fixed32,10,opt,name=TotalDue,proto3" json:"TotalDue,omitempty"`
	ModifiedDate         string      `protobuf:"bytes,11,opt,name=ModifiedDate,proto3" json:"ModifiedDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PurchaseOrderInfo) Reset()         { *m = PurchaseOrderInfo{} }
func (m *PurchaseOrderInfo) String() string { return proto.CompactTextString(m) }
func (*PurchaseOrderInfo) ProtoMessage()    {}
func (*PurchaseOrderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2959e34eedd76869, []int{12}
}

func (m *PurchaseOrderInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PurchaseOrderInfo.Unmarshal(m, b)
}
func (m *PurchaseOrderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PurchaseOrderInfo.Marshal(b, m, deterministic)
}
func (m *PurchaseOrderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PurchaseOrderInfo.Merge(m, src)
}
func (m *PurchaseOrderInfo) XXX_Size() int {
	return xxx_messageInfo_PurchaseOrderInfo.Size(m)
}
func (m *PurchaseOrderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PurchaseOrderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PurchaseOrderInfo proto.InternalMessageInfo

func (m *PurchaseOrderInfo) GetEmployeeInfo() *Employee {
	if m != nil {
		return m.EmployeeInfo
	}
	return nil
}

func (m *PurchaseOrderInfo) GetVendorInfo() *VendorInfo {
	if m != nil {
		return m.VendorInfo
	}
	return nil
}

func (m *PurchaseOrderInfo) GetShipMethod() *ShipMethod {
	if m != nil {
		return m.ShipMethod
	}
	return nil
}

func (m *PurchaseOrderInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *PurchaseOrderInfo) GetOrderDate() string {
	if m != nil {
		return m.OrderDate
	}
	return ""
}

func (m *PurchaseOrderInfo) GetShipDate() string {
	if m != nil {
		return m.ShipDate
	}
	return ""
}

func (m *PurchaseOrderInfo) GetSubTotal() float32 {
	if m != nil {
		return m.SubTotal
	}
	return 0
}

func (m *PurchaseOrderInfo) GetTaxAmt() float32 {
	if m != nil {
		return m.TaxAmt
	}
	return 0
}

func (m *PurchaseOrderInfo) GetFreight() float32 {
	if m != nil {
		return m.Freight
	}
	return 0
}

func (m *PurchaseOrderInfo) GetTotalDue() float32 {
	if m != nil {
		return m.TotalDue
	}
	return 0
}

func (m *PurchaseOrderInfo) GetModifiedDate() string {
	if m != nil {
		return m.ModifiedDate
	}
	return ""
}

func init() {
	proto.RegisterType((*AddNewVendorReq)(nil), "mssql_server.AddNewVendorReq")
	proto.RegisterType((*GetVendorReq)(nil), "mssql_server.GetVendorReq")
	proto.RegisterType((*PurchaseOrderInfoReq)(nil), "mssql_server.PurchaseOrderInfoReq")
	proto.RegisterType((*ListVendorResp)(nil), "mssql_server.ListVendorResp")
	proto.RegisterType((*VendorInfo)(nil), "mssql_server.VendorInfo")
	proto.RegisterType((*ListShipMethodResp)(nil), "mssql_server.ListShipMethodResp")
	proto.RegisterType((*ShipMethod)(nil), "mssql_server.ShipMethod")
	proto.RegisterType((*PurchaseOrderHeader)(nil), "mssql_server.PurchaseOrderHeader")
	proto.RegisterType((*PurchaseOrderDetail)(nil), "mssql_server.PurchaseOrderDetail")
	proto.RegisterType((*Product)(nil), "mssql_server.Product")
	proto.RegisterType((*ProductVendor)(nil), "mssql_server.ProductVendor")
	proto.RegisterType((*Employee)(nil), "mssql_server.Employee")
	proto.RegisterType((*PurchaseOrderInfo)(nil), "mssql_server.PurchaseOrderInfo")
}

func init() {
	proto.RegisterFile("mssql_server/proto/v1/mssql_server.proto", fileDescriptor_2959e34eedd76869)
}

var fileDescriptor_2959e34eedd76869 = []byte{
	// 1544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x57, 0x4b, 0x77, 0x13, 0x47,
	0x16, 0x3e, 0xb2, 0x8c, 0x6d, 0x95, 0x25, 0x03, 0xe5, 0x07, 0x3d, 0xc2, 0x80, 0xa6, 0x99, 0x61,
	0x3c, 0x1c, 0xb0, 0xc0, 0x33, 0x9b, 0x84, 0x95, 0x41, 0xc6, 0x38, 0xb1, 0x8c, 0xd3, 0x52, 0xc2,
	0x39, 0x6c, 0x74, 0x4a, 0xdd, 0x57, 0x72, 0x85, 0x56, 0x57, 0x53, 0x5d, 0x2d, 0x23, 0x38, 0x6c,
	0xb2, 0xce, 0x2a, 0xd9, 0x65, 0x97, 0x4d, 0xb2, 0xcc, 0x8f, 0xc9, 0x4f, 0x48, 0x76, 0x59, 0xe5,
	0x1f, 0xe4, 0xd4, 0x43, 0xad, 0xee, 0x56, 0x1b, 0xb2, 0x92, 0xee, 0x77, 0x6f, 0x3d, 0xee, 0x77,
	0x1f, 0x7d, 0x0b, 0xed, 0x8c, 0xa2, 0xe8, 0xb5, 0xdf, 0x8b, 0x80, 0x8f, 0x81, 0x37, 0x43, 0xce,
	0x04, 0x6b, 0x8e, 0x1f, 0x36, 0xd3, 0xe8, 0xae, 0x42, 0x71, 0x35, 0x8d, 0xd5, 0xb7, 0x87, 0x8c,
	0x0d, 0x7d, 0x68, 0x92, 0x90, 0x36, 0x49, 0x10, 0x30, 0x41, 0x04, 0x65, 0x41, 0xa4, 0x6d, 0xeb,
	0xd7, 0x8d, 0x56, 0x49, 0xfd, 0x78, 0xd0, 0x84, 0x51, 0x28, 0x26, 0x46, 0x79, 0x4f, 0xfd, 0xb8,
	0xf7, 0x87, 0x10, 0xdc, 0x8f, 0xce, 0xc9, 0x70, 0x08, 0xbc, 0xc9, 0x42, 0xb5, 0x7c, 0x7e, 0x2b,
	0xdb, 0x45, 0x97, 0xf7, 0x3d, 0xef, 0x04, 0xce, 0xbf, 0x82, 0xc0, 0x63, 0xdc, 0x81, 0xd7, 0x18,
	0xa3, 0xc5, 0x80, 0x8c, 0xc0, 0x2a, 0x35, 0x4a, 0x3b, 0x15, 0x47, 0xfd, 0xc7, 0xb7, 0x51, 0xcd,
	0xe5, 0xe0, 0x51, 0xd1, 0xe3, 0x44, 0xd0, 0x60, 0x68, 0x2d, 0x28, 0x65, 0x55, 0x83, 0x8e, 0xc2,
	0xf0, 0x35, 0xb4, 0x1c, 0x73, 0xbf, 0x77, 0x0e, 0x7d, 0xab, 0xac, 0xd4, 0x4b, 0x31, 0xf7, 0x5f,
	0x40, 0xdf, 0xb6, 0x51, 0xf5, 0x10, 0x44, 0xe6, 0x04, 0x31, 0x09, 0x93, 0x13, 0xe4, 0x7f, 0xfb,
	0x0e, 0xda, 0x38, 0x8d, 0xb9, 0x7b, 0x46, 0x22, 0x78, 0xce, 0x3d, 0xe0, 0x47, 0xc1, 0x80, 0x49,
	0xdb, 0x35, 0xb4, 0x40, 0x3d, 0x65, 0x59, 0x73, 0x16, 0xa8, 0x67, 0x7f, 0x8e, 0xd6, 0x8e, 0x69,
	0x94, 0x6c, 0x16, 0x85, 0xf8, 0x13, 0xb4, 0x3a, 0x56, 0x52, 0x8f, 0x06, 0x03, 0x66, 0x95, 0x1a,
	0xe5, 0x9d, 0xd5, 0x3d, 0x6b, 0x37, 0xc3, 0xb1, 0x36, 0x57, 0x7b, 0xa2, 0x71, 0xf2, 0xdf, 0xfe,
	0xb1, 0x84, 0xd0, 0x4c, 0x55, 0xe8, 0xf9, 0x0d, 0x84, 0x88, 0xeb, 0xf6, 0x82, 0x78, 0xd4, 0x07,
	0x6e, 0xdc, 0xae, 0x10, 0xd7, 0x3d, 0x51, 0xc0, 0x3c, 0x31, 0xe5, 0x02, 0x62, 0x6e, 0xa3, 0x5a,
	0xc8, 0x61, 0x00, 0xbc, 0xa7, 0xcf, 0xb6, 0x16, 0x1b, 0xa5, 0x9d, 0x15, 0xa7, 0xaa, 0x41, 0x7d,
	0x01, 0xbc, 0x85, 0x96, 0x88, 0x2b, 0xe8, 0x18, 0xac, 0x4b, 0x4a, 0x6b, 0x24, 0xfb, 0x39, 0xc2,
	0xd2, 0xe1, 0xce, 0x19, 0x0d, 0xdb, 0x20, 0xce, 0x98, 0x37, 0x75, 0x3a, 0x3a, 0xa3, 0x61, 0x6f,
	0xa4, 0xa0, 0x62, 0xa7, 0x53, 0x4b, 0x50, 0x94, 0xfc, 0xb7, 0x5f, 0x22, 0x34, 0xd3, 0x14, 0xfa,
	0x7c, 0x1d, 0x55, 0xd4, 0xe6, 0x7d, 0x12, 0x81, 0x72, 0x79, 0xc1, 0x59, 0x91, 0xc0, 0x63, 0x12,
	0xcd, 0x94, 0x9c, 0x08, 0x50, 0xde, 0x1a, 0xa5, 0x43, 0x04, 0xd8, 0x3f, 0x97, 0xd1, 0x7a, 0x26,
	0x8c, 0xcf, 0x80, 0x78, 0xc0, 0xf1, 0x0e, 0xba, 0x9c, 0x8d, 0x6e, 0xcb, 0x84, 0x34, 0x0f, 0xe3,
	0x3b, 0x68, 0xcd, 0x81, 0x31, 0x8d, 0x28, 0x0b, 0x4e, 0x66, 0x9c, 0xd7, 0x9c, 0x1c, 0x2a, 0xe9,
	0xea, 0x08, 0x22, 0xe2, 0x48, 0xdd, 0xa1, 0xe6, 0x18, 0x09, 0xdf, 0x44, 0xe8, 0x60, 0x14, 0xfa,
	0x6c, 0x02, 0x70, 0xd4, 0x52, 0x44, 0xd7, 0x9c, 0x14, 0x82, 0xeb, 0x68, 0xc5, 0x44, 0xbc, 0xa5,
	0x88, 0xae, 0x39, 0x89, 0x8c, 0x6d, 0x54, 0x9d, 0x31, 0x73, 0xd4, 0xb2, 0x96, 0x94, 0x3e, 0x83,
	0xe1, 0x6d, 0x54, 0x51, 0x57, 0x6d, 0x49, 0xf7, 0x97, 0x75, 0x3a, 0x24, 0x80, 0xdc, 0x5d, 0x5a,
	0x2b, 0xe5, 0x8a, 0x52, 0x26, 0xb2, 0xd2, 0xc5, 0xfd, 0x2e, 0x13, 0xc4, 0xb7, 0x2a, 0x9a, 0xb7,
	0xa9, 0x2c, 0xbd, 0xe9, 0x92, 0x37, 0xfb, 0x23, 0x61, 0x21, 0xa5, 0x31, 0x12, 0xb6, 0xd0, 0xf2,
	0x53, 0x0e, 0x74, 0x78, 0x26, 0xac, 0x55, 0xa5, 0x98, 0x8a, 0x72, 0x37, 0xb5, 0xb4, 0x15, 0x83,
	0x55, 0xd5, 0xbb, 0x4d, 0x65, 0xe9, 0x47, 0x9b, 0x79, 0x74, 0x40, 0xc1, 0x53, 0x37, 0xa9, 0xe9,
	0x9c, 0x4c, 0x63, 0xf6, 0x6f, 0x0b, 0xb9, 0x48, 0xb5, 0x40, 0x10, 0xea, 0xe3, 0xff, 0xa3, 0xcd,
	0x02, 0x38, 0x89, 0x57, 0xb1, 0x52, 0xde, 0xb3, 0x15, 0x83, 0x3a, 0x4c, 0x97, 0xc8, 0x54, 0x94,
	0xf7, 0x54, 0xa6, 0x5f, 0x88, 0x89, 0x89, 0x54, 0x22, 0x4b, 0x2e, 0x4f, 0x39, 0xf3, 0x62, 0x57,
	0x24, 0xa1, 0x9a, 0x01, 0x52, 0xfb, 0x65, 0x40, 0xc5, 0x29, 0xa7, 0x2e, 0x98, 0x50, 0xcd, 0x00,
	0xa9, 0x3d, 0xa6, 0x01, 0x68, 0x3a, 0x97, 0x74, 0x1c, 0x12, 0x00, 0x37, 0xd0, 0xaa, 0x03, 0x2e,
	0xd0, 0x31, 0x78, 0xf2, 0x60, 0x1d, 0xa7, 0x34, 0xa4, 0x2d, 0xbe, 0x06, 0x57, 0x68, 0x8b, 0x15,
	0xb5, 0x7f, 0x1a, 0x92, 0x99, 0xd4, 0x11, 0xcc, 0x7d, 0xa5, 0x0d, 0x2a, 0x3a, 0x93, 0x66, 0xc8,
	0x1c, 0xcb, 0xa8, 0x80, 0xe5, 0x3f, 0x97, 0xd0, 0xb2, 0xf1, 0x28, 0xeb, 0x6d, 0x29, 0xef, 0x2d,
	0x46, 0x8b, 0x27, 0xb2, 0x0e, 0x35, 0x7d, 0xea, 0x3f, 0xfe, 0x17, 0xaa, 0x19, 0x03, 0x53, 0x0a,
	0xba, 0xb9, 0x64, 0x41, 0xc9, 0x70, 0x9b, 0xbc, 0x82, 0xa7, 0x3e, 0x19, 0x9a, 0xc6, 0x92, 0xc8,
	0xf8, 0x1e, 0xba, 0xfa, 0x94, 0x06, 0x34, 0x3a, 0x03, 0xef, 0x90, 0x31, 0x2f, 0x52, 0x46, 0xba,
	0xbf, 0xcc, 0x2b, 0xf0, 0x06, 0xba, 0xf4, 0x84, 0xf9, 0x8c, 0x1b, 0x3e, 0xb5, 0x80, 0xef, 0xa2,
	0x2b, 0x1d, 0x32, 0x00, 0x31, 0x51, 0xbe, 0x1f, 0xc3, 0x18, 0x7c, 0x45, 0x68, 0xcd, 0x99, 0xc3,
	0x25, 0x27, 0x0e, 0x30, 0x19, 0xdf, 0x53, 0x46, 0x03, 0x61, 0x68, 0xcd, 0x60, 0xaa, 0xca, 0x04,
	0x09, 0x3c, 0xc2, 0xbd, 0x27, 0x2c, 0x12, 0x86, 0xd9, 0x0c, 0xa6, 0xa3, 0x1b, 0x99, 0xd8, 0x23,
	0xcd, 0x55, 0x02, 0x48, 0xae, 0x3a, 0xf4, 0x2d, 0xa8, 0x92, 0xa8, 0x38, 0xea, 0x3f, 0x7e, 0x80,
	0xd6, 0xe5, 0xaf, 0x4c, 0x90, 0x36, 0x90, 0x28, 0xe6, 0xf0, 0x84, 0x79, 0xba, 0x34, 0x2a, 0x4e,
	0x91, 0x4a, 0x66, 0xfa, 0x0b, 0x55, 0x4b, 0xf9, 0x35, 0xba, 0x5c, 0x8a, 0x95, 0xb2, 0x52, 0xb5,
	0xc2, 0x5a, 0xd3, 0x7d, 0x47, 0x4b, 0x92, 0xe9, 0x16, 0x99, 0x44, 0x5d, 0xd6, 0x26, 0x41, 0x3c,
	0x20, 0xae, 0x88, 0x39, 0x58, 0x97, 0x95, 0xc9, 0xbc, 0x42, 0x66, 0x9f, 0x09, 0xa2, 0xcc, 0x59,
	0xeb, 0x8a, 0xce, 0xcf, 0x14, 0xa4, 0x62, 0xe1, 0x93, 0x28, 0xb2, 0xae, 0x9a, 0x58, 0x48, 0x41,
	0xa2, 0x1d, 0x31, 0xf1, 0xc1, 0xc2, 0x1a, 0x55, 0x02, 0xde, 0x43, 0x1b, 0x66, 0x69, 0x27, 0xee,
	0xbb, 0x44, 0xc0, 0x90, 0xf1, 0xc9, 0x51, 0xcb, 0x5a, 0x57, 0xc7, 0x17, 0xea, 0x64, 0x9f, 0x35,
	0x78, 0x9b, 0x79, 0x20, 0x0b, 0x7c, 0x43, 0xf7, 0xd9, 0x2c, 0x2a, 0x73, 0xb0, 0x03, 0xbe, 0xdf,
	0x11, 0x84, 0x0b, 0x95, 0xe6, 0x9b, 0x3a, 0x07, 0x33, 0xa0, 0xf4, 0x47, 0x02, 0x07, 0x81, 0x2e,
	0x85, 0x2d, 0xed, 0x4f, 0x0a, 0x92, 0x59, 0xd4, 0xa2, 0x91, 0xcb, 0x02, 0x41, 0x83, 0xd8, 0x54,
	0xcc, 0x35, 0x65, 0x36, 0x87, 0xcb, 0x6e, 0xc2, 0xd9, 0xf9, 0x30, 0xa6, 0x9e, 0x65, 0xe9, 0x6e,
	0x62, 0xc4, 0xb9, 0x9a, 0xfb, 0x47, 0x41, 0xcd, 0xfd, 0x52, 0x4e, 0xca, 0xc6, 0x7c, 0x5a, 0x3f,
	0x5c, 0x79, 0x77, 0xd1, 0x95, 0xc7, 0x71, 0x44, 0x03, 0x88, 0xa2, 0x83, 0x40, 0x50, 0x21, 0x99,
	0xd3, 0xdf, 0x9c, 0x39, 0x5c, 0x7e, 0xc7, 0xf6, 0xc7, 0xc0, 0xc9, 0x10, 0x8e, 0x81, 0x78, 0x5d,
	0x3a, 0x02, 0xd3, 0xd4, 0xf2, 0xb0, 0xe2, 0xcd, 0x64, 0xb4, 0xce, 0x62, 0xdd, 0xdf, 0xb2, 0xa0,
	0xdc, 0xef, 0x98, 0x44, 0x42, 0x35, 0xa6, 0x50, 0xa8, 0x72, 0xd0, 0x9d, 0x2e, 0x0f, 0xe7, 0x2c,
	0x95, 0xf3, 0xba, 0x4a, 0xf3, 0xb0, 0x8c, 0x45, 0x9b, 0x06, 0x49, 0xd3, 0xd5, 0xa5, 0x9a, 0x86,
	0x94, 0x05, 0x79, 0x93, 0x58, 0x98, 0xde, 0x97, 0x82, 0x64, 0xef, 0x7b, 0x3e, 0xdb, 0xc2, 0xf4,
	0xbe, 0x19, 0x22, 0x6f, 0x93, 0xaf, 0x1a, 0xdd, 0xfe, 0xf2, 0xf0, 0x5c, 0xc4, 0x56, 0x0b, 0x22,
	0xf6, 0x43, 0x09, 0xad, 0x4c, 0x3f, 0xd1, 0xb2, 0x9d, 0x7d, 0xc6, 0xfa, 0x5d, 0x2a, 0xfc, 0xe9,
	0x50, 0x92, 0xc8, 0xb2, 0xf8, 0x0e, 0x21, 0xf0, 0x92, 0x41, 0xcc, 0x48, 0x32, 0x99, 0x5b, 0x10,
	0x12, 0x2e, 0x46, 0x10, 0x08, 0xd5, 0x46, 0x75, 0xa7, 0xcc, 0xa1, 0x32, 0x11, 0x0e, 0x39, 0x8b,
	0x43, 0x65, 0xb2, 0xa8, 0x3f, 0x1a, 0x09, 0xa0, 0x8a, 0xeb, 0x8c, 0x0e, 0x74, 0x08, 0x64, 0x71,
	0x49, 0xc1, 0xfe, 0xa9, 0x8c, 0xae, 0xce, 0x4d, 0xa6, 0xf8, 0x11, 0xaa, 0x81, 0xb9, 0xf1, 0x74,
	0xec, 0x2c, 0xed, 0xac, 0xee, 0x6d, 0x65, 0x27, 0xb0, 0xa9, 0x53, 0x4e, 0x75, 0x6a, 0xac, 0x16,
	0xe7, 0x26, 0xd6, 0x05, 0xb5, 0xf4, 0x6f, 0x4d, 0xac, 0xf9, 0xb9, 0xaf, 0x5c, 0xb4, 0xb4, 0x78,
	0xee, 0x4b, 0x4d, 0x4c, 0xda, 0xf3, 0xe9, 0xc4, 0x94, 0x99, 0x68, 0x2e, 0x7d, 0x68, 0xa2, 0x59,
	0xfa, 0xc0, 0x44, 0xb3, 0x7c, 0xe1, 0x44, 0xb3, 0x72, 0xd1, 0x44, 0x53, 0xb9, 0x78, 0xa2, 0x41,
	0x1f, 0x99, 0x68, 0x0a, 0xb2, 0x68, 0xef, 0x8f, 0x32, 0x5a, 0xdf, 0x0f, 0xc3, 0xb6, 0xa4, 0xa2,
	0x3d, 0x1c, 0x89, 0x0e, 0xf0, 0xb1, 0xac, 0x31, 0x1f, 0x55, 0x92, 0xd7, 0x07, 0xae, 0x67, 0xa9,
	0x4a, 0x3f, 0x4b, 0xea, 0xdb, 0x59, 0x5d, 0xf6, 0x99, 0x61, 0xff, 0xfb, 0x9b, 0x5f, 0x7f, 0xff,
	0x7e, 0xe1, 0x16, 0xbe, 0xd1, 0xf4, 0x88, 0x20, 0x3d, 0xf2, 0x36, 0xe6, 0x20, 0xdf, 0x72, 0x3a,
	0x38, 0x51, 0xf3, 0x9d, 0x7c, 0xc6, 0xbc, 0xc7, 0x81, 0x7e, 0x9f, 0xa4, 0x26, 0xec, 0xad, 0x5d,
	0xfd, 0x5c, 0xdb, 0x9d, 0x3e, 0xd7, 0x64, 0x5a, 0x88, 0x49, 0xbd, 0x31, 0x7f, 0x5c, 0x76, 0xc8,
	0xb7, 0x6d, 0x75, 0xe4, 0x36, 0xae, 0xe7, 0x8e, 0x4c, 0x65, 0x00, 0xfe, 0xb6, 0x84, 0x36, 0x0e,
	0x41, 0xcc, 0x67, 0xa8, 0x9d, 0xdd, 0xbe, 0xe8, 0x71, 0x55, 0xbf, 0xf5, 0x11, 0x1b, 0xbb, 0xa9,
	0x6e, 0xf0, 0x5f, 0xfc, 0x9f, 0xdc, 0x0d, 0x42, 0x63, 0xd9, 0x53, 0xdf, 0x75, 0x95, 0xc6, 0xcd,
	0x77, 0xd4, 0x7b, 0x8f, 0x87, 0xa8, 0x9a, 0x7e, 0x4f, 0xe2, 0x1b, 0xd9, 0x13, 0x72, 0x6f, 0xcd,
	0xfa, 0x05, 0xdc, 0xd8, 0x0d, 0x75, 0x6e, 0xdd, 0xde, 0x2c, 0x24, 0xfb, 0xd3, 0xd2, 0xdd, 0xc7,
	0xad, 0xef, 0xf6, 0x6f, 0xe2, 0x6d, 0xb4, 0xf9, 0xac, 0xdb, 0x3d, 0x6d, 0x38, 0x07, 0x9d, 0x6e,
	0x63, 0xff, 0xf4, 0xa8, 0x61, 0x62, 0xbe, 0x57, 0x7e, 0xb8, 0xfb, 0xe0, 0xe5, 0x3f, 0x0b, 0x1f,
	0xdf, 0x8f, 0x14, 0xaa, 0xc1, 0xfe, 0x92, 0x42, 0xff, 0xf7, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x64, 0x79, 0x52, 0x57, 0xa8, 0x0f, 0x00, 0x00,
}
